
export type Dimension = {
  key: string;
  en: string;
  zh: string;
};

export const dimensions: Dimension[] = [
  { key: 'motivationAndPurpose', en: 'Motivation & Purpose', zh: '研究动机与目标' },
  { key: 'researchSkillsAndThinking', en: 'Research Skills & Thinking Disposition', zh: '研究能力与思维倾向' },
  { key: 'selfRegulationAndPerseverance', en: 'Self-Regulation & Perseverance', zh: '自我管理与坚持力' },
  { key: 'psychologicalCapitalAndResilience', en: 'Psychological Capital & Resilience', zh: '心理韧性与应对能力' },
  { key: 'interpersonalAndCommunication', en: 'Interpersonal & Communication Skills', zh: '人际沟通与协作' },
  { key: 'academicIntegrityAndValues', en: 'Academic Integrity & Values', zh: '学术价值观与伦理' },
  { key: 'environmentAndSupportSystem', en: 'Environment & Support System', zh: '环境与支持系统' },
  { key: 'careerOrientationAndFuture', en: 'Career Orientation & Future Vision', zh: '职业规划与长期视野' },
  { key: 'selfReflectionAndReadiness', en: 'Self-Reflection & Readiness', zh: '综合评价与主观感受' },
];

export type Question = {
  id: number;
  dimension_en: string;
  dimension_zh: string;
  dimension_key: string;
  question_en: string;
  question_zh: string;
  in_concise: boolean;
};

export const questions: Question[] = [
  // 1. Motivation & Purpose
  {
    id: 1,
    dimension_en: 'Motivation & Purpose',
    dimension_zh: '研究动机与目标',
    dimension_key: 'motivationAndPurpose',
    question_en: 'My main motivation for pursuing a PhD is a strong curiosity about my research topic.',
    question_zh: '我攻读博士的主要动机是对研究问题本身的强烈兴趣。',
    in_concise: true,
  },
  {
    id: 2,
    dimension_en: 'Motivation & Purpose',
    dimension_zh: '研究动机与目标',
    dimension_key: 'motivationAndPurpose',
    question_en: 'I have a clear understanding of why I want to earn a PhD.',
    question_zh: '我清楚地知道自己为什么想要获得博士学位。',
    in_concise: true,
  },
  {
    id: 3,
    dimension_en: 'Motivation & Purpose',
    dimension_zh: '研究动机与目标',
    dimension_key: 'motivationAndPurpose',
    question_en: 'I would still enjoy doing academic research even without external rewards.',
    question_zh: '即使没有外部奖励（如职位、金钱），我也会乐于进行学术研究。',
    in_concise: false,
  },
  {
    id: 4,
    dimension_en: 'Motivation & Purpose',
    dimension_zh: '研究动机与目标',
    dimension_key: 'motivationAndPurpose',
    question_en: 'I hope to contribute new knowledge or positive change through my doctoral research.',
    question_zh: '我希望通过博士研究为社会或学术界带来新的知识或改变。',
    in_concise: false,
  },
  {
    id: 5,
    dimension_en: 'Motivation & Purpose',
    dimension_zh: '研究动机与目标',
    dimension_key: 'motivationAndPurpose',
    question_en: 'My decision to pursue a PhD is driven by internal interest rather than external pressure.',
    question_zh: '我攻读博士的主要动力来自内心兴趣，而非外界压力或期望。',
    in_concise: false,
  },

  // 2. Research Skills & Thinking Disposition
  {
    id: 6,
    dimension_en: 'Research Skills & Thinking Disposition',
    dimension_zh: '研究能力与思维倾向',
    dimension_key: 'researchSkillsAndThinking',
    question_en: 'I can extract the core problem from complex information.',
    question_zh: '我能够从复杂的资料中提炼核心问题。',
    in_concise: true,
  },
  {
    id: 7,
    dimension_en: 'Research Skills & Thinking Disposition',
    dimension_zh: '研究能力与思维倾向',
    dimension_key: 'researchSkillsAndThinking',
    question_en: 'I enjoy formulating hypotheses and designing methods to test them.',
    question_zh: '我喜欢提出假设并设计方法去验证它。',
    in_concise: true,
  },
  {
    id: 8,
    dimension_en: 'Research Skills & Thinking Disposition',
    dimension_zh: '研究能力与思维倾向',
    dimension_key: 'researchSkillsAndThinking',
    question_en: 'I have strong critical thinking skills to identify flaws or biases in research.',
    question_zh: '我具备较强的批判性思维，能识别研究中的漏洞与偏差。',
    in_concise: false,
  },
  {
    id: 9,
    dimension_en: 'Research Skills & Thinking Disposition',
    dimension_zh: '研究能力与思维倾向',
    dimension_key: 'researchSkillsAndThinking',
    question_en: 'I am good at systematically collecting, organizing, and analyzing data.',
    question_zh: '我擅长系统性地搜集、整理与分析资料。',
    in_concise: false,
  },
  {
    id: 10,
    dimension_en: 'Research Skills & Thinking Disposition',
    dimension_zh: '研究能力与思维倾向',
    dimension_key: 'researchSkillsAndThinking',
    question_en: 'I can independently learn new theories, tools, or methods.',
    question_zh: '我能够独立学习新理论、新工具或新方法。',
    in_concise: false,
  },

  // 3. Self-Regulation & Perseverance
  {
    id: 11,
    dimension_en: 'Self-Regulation & Perseverance',
    dimension_zh: '自我管理与坚持力',
    dimension_key: 'selfRegulationAndPerseverance',
    question_en: 'I can stay self-disciplined during long periods of independent work.',
    question_zh: '我能在长时间的独立工作中保持自律。',
    in_concise: true,
  },
  {
    id: 12,
    dimension_en: 'Self-Regulation & Perseverance',
    dimension_zh: '自我管理与坚持力',
    dimension_key: 'selfRegulationAndPerseverance',
    question_en: 'I can maintain motivation even when my research progresses slowly or fails.',
    question_zh: '我能够在研究进展缓慢或失败时保持动力。',
    in_concise: true,
  },
  {
    id: 13,
    dimension_en: 'Self-Regulation & Perseverance',
    dimension_zh: '自我管理与坚持力',
    dimension_key: 'selfRegulationAndPerseverance',
    question_en: 'I manage my time effectively and meet deadlines.',
    question_zh: '我善于规划时间并按时完成任务。',
    in_concise: false,
  },
  {
    id: 14,
    dimension_en: 'Self-Regulation & Perseverance',
    dimension_zh: '自我管理与坚持力',
    dimension_key: 'selfRegulationAndPerseverance',
    question_en: 'I stay patient when facing complex or ambiguous problems.',
    question_zh: '我能在面对复杂或模糊的问题时耐心寻找解决方案。',
    in_concise: false,
  },
  {
    id: 15,
    dimension_en: 'Self-Regulation & Perseverance',
    dimension_zh: '自我管理与坚持力',
    dimension_key: 'selfRegulationAndPerseverance',
    question_en: 'I proactively seek resources or help when encountering research difficulties.',
    question_zh: '我能主动寻求资源或帮助以克服研究中的困难。',
    in_concise: false,
  },
  
  // 4. Psychological Capital & Resilience
  {
    id: 16,
    dimension_en: 'Psychological Capital & Resilience',
    dimension_zh: '心理韧性与应对能力',
    dimension_key: 'psychologicalCapitalAndResilience',
    question_en: 'I can quickly regain confidence after academic rejection (e.g., paper rejection).',
    question_zh: '即使遭遇学术拒绝（如论文被拒），我也能迅速恢复信心。',
    in_concise: true,
  },
  {
    id: 17,
    dimension_en: 'Psychological Capital & Resilience',
    dimension_zh: '心理韧性与应对能力',
    dimension_key: 'psychologicalCapitalAndResilience',
    question_en: 'I believe I am capable of completing a PhD successfully.',
    question_zh: '我相信自己有能力完成博士研究。',
    in_concise: true,
  },
  {
    id: 18,
    dimension_en: 'Psychological Capital & Resilience',
    dimension_zh: '心理韧性与应对能力',
    dimension_key: 'psychologicalCapitalAndResilience',
    question_en: 'When facing uncertainty, I tend to respond proactively rather than avoid it.',
    question_zh: '面对不确定性时，我倾向于积极应对而非逃避。',
    in_concise: false,
  },
  {
    id: 19,
    dimension_en: 'Psychological Capital & Resilience',
    dimension_zh: '心理韧性与应对能力',
    dimension_key: 'psychologicalCapitalAndResilience',
    question_en: 'I can stay emotionally stable under pressure.',
    question_zh: '我能在压力大的时候保持心理稳定。',
    in_concise: false,
  },
  {
    id: 20,
    dimension_en: 'Psychological Capital & Resilience',
    dimension_zh: '心理韧性与应对能力',
    dimension_key: 'psychologicalCapitalAndResilience',
    question_en: 'I learn from failure rather than giving up.',
    question_zh: '我能从失败中学习，而不是因此放弃。',
    in_concise: false,
  },

  // 5. Interpersonal & Communication Skills
  {
    id: 21,
    dimension_en: 'Interpersonal & Communication Skills',
    dimension_zh: '人际沟通与协作',
    dimension_key: 'interpersonalAndCommunication',
    question_en: 'I can have open and rational discussions with my supervisor or peers.',
    question_zh: '我能与导师或同事进行开放而理性的讨论。',
    in_concise: true,
  },
  {
    id: 22,
    dimension_en: 'Interpersonal & Communication Skills',
    dimension_zh: '人际沟通与协作',
    dimension_key: 'interpersonalAndCommunication',
    question_en: 'I can communicate my research ideas clearly and accept constructive feedback.',
    question_zh: '我善于表达自己的研究想法并接受反馈。',
    in_concise: true,
  },
  {
    id: 23,
    dimension_en: 'Interpersonal & Communication Skills',
    dimension_zh: '人际沟通与协作',
    dimension_key: 'interpersonalAndCommunication',
    question_en: 'I can work effectively in collaborative research projects.',
    question_zh: '我能够在团队研究中有效地合作。',
    in_concise: false,
  },
  {
    id: 24,
    dimension_en: 'Interpersonal & Communication Skills',
    dimension_zh: '人际沟通与协作',
    dimension_key: 'interpersonalAndCommunication',
    question_en: 'I am willing to listen to others’ opinions, even when they differ from mine.',
    question_zh: '我愿意倾听他人意见，即使它与我不同。',
    in_concise: false,
  },
  {
    id: 25,
    dimension_en: 'Interpersonal & Communication Skills',
    dimension_zh: '人际沟通与协作',
    dimension_key: 'interpersonalAndCommunication',
    question_en: 'I can adapt to multicultural or interdisciplinary research environments.',
    question_zh: '我能适应多元文化或跨学科研究环境。',
    in_concise: false,
  },

  // 6. Academic Integrity & Values
  {
    id: 26,
    dimension_en: 'Academic Integrity & Values',
    dimension_zh: '学术价值观与伦理',
    dimension_key: 'academicIntegrityAndValues',
    question_en: 'I value honesty and transparency in all research activities.',
    question_zh: '我坚持在研究中保持诚实与透明。',
    in_concise: true,
  },
  {
    id: 27,
    dimension_en: 'Academic Integrity & Values',
    dimension_zh: '学术价值观与伦理',
    dimension_key: 'academicIntegrityAndValues',
    question_en: 'I would not manipulate or fabricate data, even under pressure.',
    question_zh: '即使有压力，我也不会篡改或伪造数据。',
    in_concise: true,
  },
  {
    id: 28,
    dimension_en: 'Academic Integrity & Values',
    dimension_zh: '学术价值观与伦理',
    dimension_key: 'academicIntegrityAndValues',
    question_en: 'I respect others’ intellectual contributions and cite sources properly.',
    question_zh: '我尊重他人的知识成果并正确引用来源。',
    in_concise: false,
  },
  {
    id: 29,
    dimension_en: 'Academic Integrity & Values',
    dimension_zh: '学术价值观与伦理',
    dimension_key: 'academicIntegrityAndValues',
    question_en: 'I understand the serious consequences of academic misconduct.',
    question_zh: '我清楚学术不端行为的严重后果。',
    in_concise: false,
  },
  {
    id: 30,
    dimension_en: 'Academic Integrity & Values',
    dimension_zh: '学术价值观与伦理',
    dimension_key: 'academicIntegrityAndValues',
    question_en: 'I believe the ultimate goal of scholarship is the pursuit of truth, not fame or profit.',
    question_zh: '我认为学术的最终目标是追求真理而非名利。',
    in_concise: false,
  },

  // 7. Environment & Support System
  {
    id: 31,
    dimension_en: 'Environment & Support System',
    dimension_zh: '环境与支持系统',
    dimension_key: 'environmentAndSupportSystem',
    question_en: 'I understand the research direction and culture of my intended program or supervisor.',
    question_zh: '我已了解目标学校或导师的研究方向与文化。',
    in_concise: true,
  },
  {
    id: 32,
    dimension_en: 'Environment & Support System',
    dimension_zh: '环境与支持系统',
    dimension_key: 'environmentAndSupportSystem',
    question_en: 'My financial situation or scholarships can adequately support my PhD study.',
    question_zh: '我的经济状况或奖学金足以支持博士学习。',
    in_concise: true,
  },
  {
    id: 33,
    dimension_en: 'Environment & Support System',
    dimension_zh: '环境与支持系统',
    dimension_key: 'environmentAndSupportSystem',
    question_en: 'My family or partner understands and supports my decision to pursue a PhD.',
    question_zh: '我的家人或伴侣理解并支持我攻读博士的决定。',
    in_concise: false,
  },
  {
    id: 34,
    dimension_en: 'Environment & Support System',
    dimension_zh: '环境与支持系统',
    dimension_key: 'environmentAndSupportSystem',
    question_en: 'I have access to necessary research resources (equipment, data, collaborations).',
    question_zh: '我有获取研究资源（如设备、数据、合作机会）的渠道。',
    in_concise: false,
  },
  {
    id: 35,
    dimension_en: 'Environment & Support System',
    dimension_zh: '环境与支持系统',
    dimension_key: 'environmentAndSupportSystem',
    question_en: 'I believe the research environment I aim for suits my personal and academic growth.',
    question_zh: '我认为我所选的研究环境适合我的成长。',
    in_concise: false,
  },

  // 8. Career Orientation & Future Vision
  {
    id: 36,
    dimension_en: 'Career Orientation & Future Vision',
    dimension_zh: '职业规划与长期视野',
    dimension_key: 'careerOrientationAndFuture',
    question_en: 'I have a clear vision for my career after completing the PhD.',
    question_zh: '我清楚自己博士毕业后的职业方向。',
    in_concise: true,
  },
  {
    id: 37,
    dimension_en: 'Career Orientation & Future Vision',
    dimension_zh: '职业规划与长期视野',
    dimension_key: 'careerOrientationAndFuture',
    question_en: 'I understand how the PhD aligns with my long-term career goals.',
    question_zh: '我知道博士学位如何与我长期的职业目标相连接。',
    in_concise: true,
  },
  {
    id: 38,
    dimension_en: 'Career Orientation & Future Vision',
    dimension_zh: '职业规划与长期视野',
    dimension_key: 'careerOrientationAndFuture',
    question_en: 'I am not pursuing a PhD merely for the degree itself.',
    question_zh: '我不只是为了“学历”而攻读博士。',
    in_concise: false,
  },
  {
    id: 39,
    dimension_en: 'Career Orientation & Future Vision',
    dimension_zh: '职业规划与长期视野',
    dimension_key: 'careerOrientationAndFuture',
    question_en: 'I am aware of the job market and challenges after earning a PhD.',
    question_zh: '我了解博士毕业后就业市场和现实挑战。',
    in_concise: false,
  },
  {
    id: 40,
    dimension_en: 'Career Orientation & Future Vision',
    dimension_zh: '职业规划与长期视野',
    dimension_key: 'careerOrientationAndFuture',
    question_en: 'Even if I don’t stay in academia, I still see PhD training as valuable.',
    question_zh: '即使未来不走学术路，我也认为博士训练对我有价值。',
    in_concise: false,
  },

  // 9. Self-Reflection & Readiness
  {
    id: 41,
    dimension_en: 'Self-Reflection & Readiness',
    dimension_zh: '综合评价与主观感受',
    dimension_key: 'selfReflectionAndReadiness',
    question_en: 'I am mentally prepared for the loneliness, pressure, and uncertainty of PhD life.',
    question_zh: '我已经做好迎接博士生活中孤独、压力与不确定性的心理准备。',
    in_concise: true,
  },
  {
    id: 42,
    dimension_en: 'Self-Reflection & Readiness',
    dimension_zh: '综合评价与主观感受',
    dimension_key: 'selfReflectionAndReadiness',
    question_en: 'My previous academic or research experience gives me confidence to continue.',
    question_zh: '我在本科或硕士阶段的学习／研究表现让我有信心继续深造。',
    in_concise: true,
  },
  {
    id: 43,
    dimension_en: 'Self-Reflection & Readiness',
    dimension_zh: '综合评价与主观感受',
    dimension_key: 'selfReflectionAndReadiness',
    question_en: 'I can stay patient and focused even when long-term goals are unclear.',
    question_zh: '我能在长期目标不确定的情况下保持耐心和方向感。',
    in_concise: false,
  },
  {
    id: 44,
    dimension_en: 'Self-Reflection & Readiness',
    dimension_zh: '综合评价与主观感受',
    dimension_key: 'selfReflectionAndReadiness',
    question_en: 'I am willing to devote significant time and effort to research, even at personal cost.',
    question_zh: '我愿意为研究投入大量时间和精力，即使影响个人生活。',
    in_concise: false,
  },
  {
    id: 45,
    dimension_en: 'Self-Reflection & Readiness',
    dimension_zh: '综合评价与主观感受',
    dimension_key: 'selfReflectionAndReadiness',
    question_en: 'If I had the chance to start a PhD now, I would feel excited rather than afraid.',
    question_zh: '如果现在有机会开始博士研究，我会感到兴奋而非恐惧。',
    in_concise: false,
  },
];
